### ISSUE TITLE
Clean bad instances out of CE env

### ISSUE THREAD

**Issue by lukevance** [ghchinoy/cectl#1]
It would be really nice to have a command that would hit the `/ping` endpoint on each instance, and shows instances that return a `4xx` code, or maybe just deletes them. 

Could be something like 
```
cectl instances test
```
and/or
```
cectl instances clean [--remove || --update]
```

**Comment by ghchinoy** [comment]
Example of use

```
$  cectl instances test

Checking 33 instances
Salesforce Sales Cloud (ce sfdc) 401 Unauthorized
ServiceNow OAuth (GHC Dev ServiceNow) 500 Internal Server Error
```

**Comment by ghchinoy** [comment]
Kelly also wants this, add in a `--remove` flag
