### ISSUE TITLE
multiple common objects / one instance - cloning capability

### ISSUE THREAD

**Issue by daniellelaforte** [ghchinoy/cectl#16]
https://docs.google.com/document/d/1aXyGLrp3G6gRZxM9n4hKOywxADvUYkTIpm-3Lsobrn8/edit?usp=sharing

**Comment by ghchinoy** [comment]
I've added two commands
* `resources copy <resource> <new_resource>` which copies a "resource" to a "new_resource" that also has an optional flag `--deep` which will also copy the Transformations associated with Elements to the "new_resource"
* `transformations delete <resource> <element>` to remove a Transformation association from an Element, which is a prerequisite, if one were wanting to delete a resource, as all the Transformations would need to be deleted before the resource could be deleted (i.e. `resources delete <resource>` will 409 if Transformations aren't first removed)

Please reopen if this doesn't address your issue
