### ISSUE TITLE
Unable to import an exported element - Error: JSON doesn’t appear to be an element

### ISSUE THREAD

**Issue by gdesouter** [ghchinoy/cectl#5]
bash-3.2$ cectl elements import e-conomic-1.json --profile cardlay-eu 
JSON doesn't appear to be an Element

**Comment by ghchinoy** [comment]
fixed in https://github.com/ghchinoy/ce-go/commit/51b7d9857019fe2864895955f730ab7ee45de8f9 and available in [v0.5.1](https://github.com/ghchinoy/cectl/releases/tag/v0.5.1)
