### ISSUE TITLE
Add some helper text to a few resource commands

### ISSUE THREAD

**Issue by lukevance** [ghchinoy/cectl#7]
The `resources definition` and `resources delete` commands require a resource name. But unlike the other `resources` commands, when you use the `--help` flag the helper text does not reflect usage as `cectl resources definition <name>`.

**Comment by lukevance** [comment]
I was going to submit a tiny PR but I don't have access 😢

**Comment by ghchinoy** [comment]
Oh no! pls fork and PR

**Comment by ghchinoy** [comment]
pls try again :)
